name: Build vpaSTRM

on:
  push:
    branches: [ v1.x, v1.x-dev ]
  pull_request:
    branches: [ v1.x, v1.x-dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure
        run: sudo apt-get install -y libavcodec-dev libavformat-dev

      - name: Build
        run: |
          ls  
        shell: bash
        
