name: Build vpaSTRM

on:
  push:
    branches: [ v1.x, v1.x-dev ]
  pull_request:
    branches: [ v1.x, v1.x-dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build project
      uses: skx/github-action-build@master
      with: 
        builder: ./vpaSTRM.sh
