name: Codacy Analysis 

on:
  push:
    branches: [ v1.x, v1.x-dev ]
  pull_request:
    branches: [ v1.x, v1.x-dev ]


jobs:
  codacy-analysis-cli:
    name: Codacy Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}

